spring.datasource.url=jdbc:postgresql://localhost:5432/gpo_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
